[GLOBAL]
pants_version = "2.17.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
    "pants_backend_makeself",
    "pants.backend.experimental.python.lint.ruff",
    "pants.backend.plugin_development",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.shell",
]

[source]
root_patterns = [
    "/",
    "pants-plugins",
]

[python]
interpreter_constraints = [">=3.7,<3.10"]
enable_resolves = true

[python-infer]
use_rust_parser = true

[python.resolves]
python-default = "lockfiles/python-default.lock"

[generate-lockfiles]
diff = true

[isort]
args=["--profile", "black"]
